spring.application.name=zerotrustapi
server.port=8081

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
refresh-token.expiration=${REFRESH_TOKEN_EXPIRATION}

mfa.challenge.expiration=300000

storage.s3.endpoint=${SUPABASE_S3_ENDPOINT}
storage.s3.access-key=${SUPABASE_S3_ACCESS_KEY}
storage.s3.secret-key=${SUPABASE_S3_SECRET_KEY}
storage.s3.region=${SUPABASE_S3_REGION}
storage.s3.bucket=${SUPABASE_BUCKET}

crypto.document-key=${DOCUMENT_ENCRYPTION_KEY}
file.max-size-bytes=${MAX_FILE_SIZE_BYTES}

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB